version: '3'

tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go

  run:
    cmds:
      - docker-compose up --build

  test:
    cmds:
      - go test -v -count=1 ./... | grep -v "no test files"